### ISSUE TITLE
Give Metro ability to add alerts

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#1010]
During the state of emergency, we added alerts to the top of the site. It would be great for Metro to be able to manage these themselves. Propose a plan to enable this functionality.

**Comment by xmedr** [comment]
@hancush Considering that some of the app's editable content is managed through UI on the site (i.e. board member info and photos), maybe we continue that trend? I can see us using either a button on the homepage, or an extra item in the nav, that lets logged in users view/add/delete alerts.

This might be done with an `Alerts` model, and it could have the `description` and `type` of the alert. Then if there are any, the template could render dismissible alerts under the nav and style them depending on their type. What do you think?

When we had alerts for the state of emergency, did the alert show up on just one page or on all pages?

**Comment by hancush** [comment]
@xmedr It showed up on all pages!

**Comment by xmedr** [comment]
@hancush Awesome, I think I can have a first draft pr by at most the EOD tomorrow!

And sounds good, I'll do the same here. How would you recommend we add that model to each template in that case? I'm seeing this [SO answer about using a custom assignment tag](https://stackoverflow.com/a/28533875) so that it would run for each template that uses `base.html` that looks promising

**Comment by shrayshray** [comment]
@camachoo what do you think? I can set up a meeting to discuss next week.

**Comment by shrayshray** [comment]
@xmedr some notes from our Metro team meeting:
- We love this feature!
- Is it possible to move the "Manage Alerts" section above the search bar? 
- Can hyperlinks be included in the alert text?
- It'd be great if there was a way to preview what the alert would look like before creating it, specifically what color it is. Is it possible to do a mouse over by the "Add New" header to show what each "type" looks like? Or have a preview/color change in the description section after the type is selected? We're open to other options for handling this, whatever you think would be most efficient.

**Comment by xmedr** [comment]
@shrayshray that's great news, I'm glad you're liking it! Thanks to your feedback, I've got some changes in and have a preview below. As for your questions, pretty much yes to all of them:

- Check the preview for what the manager can look like above the search
- The input now accepts [Markdown](https://www.markdownguide.org/cheat-sheet/#basic-syntax) to format it's output, similarly to what happens here on GitHub. So hyperlinks can be included either by pasting them in directly, or if you want them to be [displayed with different text like this](https://example.com), the link just has to be wrapped in the format `[link display text](https://example.com)`.
  - Other formatting options like **bolding**(`**bolding**`) and *italics*(`*italics*`) are now also available because of markdown
- Both the type selection box and the description input box now style themselves to preview whatever alert style is selected. Thanks for that suggestion!

Let me know if there's anything else in this you'd like to see.

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/114717958/2cf392c6-d7cf-4eef-a75c-a98b15de7d18)

**Comment by xmedr** [comment]
@shrayshray this should be good to go on live site!
