### ISSUE TITLE
Feature request: Ability to push "Listen Live" links during service interruptions effecting meeting broadcast status

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1018]
On Wednesday, 9/13/23, Granicus experienced an outage before and through the duration of the Measure M Independent Taxpayer Oversight Committee meeting. The broadcast was started, but the meeting status never changed to “In Progress”. As a result, the links to watch never showed on the site. Our understanding based on #238 is that Councilmatic uses the EVENTGUID field in the Legistar API to build the "Listen Live" links once the meeting status is "In Progress". Would it be possible to engineer a way to allow us to manually generate/build the listen links in admin mode when there is an outage like the one on Wednesday, and the meeting is live but the status has not updated? We'd like to get your thoughts on options and discuss in our next meeting.

**Comment by hancush** [comment]
The current meeting logic is as follows:

- If there is a meeting scheduled to begin in the last six hours or the next 5 minutes, hit the running events endpoint (http://metro.granicus.com/running_events.php).
- If there is a running event, return the event with the matching GUID. <--- Since Legistar was out, this step never happened, so we never observed the event being broadcast.
- If there is not a running event, return events scheduled to begin in the last 20 minutes (to account for late starts) or the next 5 minutes.

RIght now, the concept of a meeting being "ongoing" is solely a function of it appearing in the running events endpoint. We could add a way for you to manually create a record of a broadcast. If the idea is to handle instances where Legistar is totally unavailable, it would need to indicate meeting status (ongoing or concluded), and you all would be responsible for updating the status. It could automatically build the broadcast link, since we have the event GUID, or it could return the generic broadcast link, which would be more forgiving if there is any delay in marking the event as having concluded.

**Comment by hancush** [comment]
DataMade to add a way for Metro to mark an event as streaming from its detail page. Page should warn against doing this if the running events endpoint is available, and double check that the live links resolve correctly before creating the event broadcast record. Ofc, it should also return useful feedback to the user, regardless of outcome.

**Comment by neilarellano** [comment]
Hi Team,

If there is any outage on Legistar/Granicus' end we would want to be able to start the meeting, the expected logic from our end on this would be as follows:
1. Check to see if the meeting is running (if Granicus systems come back up within the duration of a currently running meeting, follow normal logic).
2. We want the ability to start the meeting within site admin panel.
3. We will need the ability to stop the meeting within the admin panel.

Thanks!

**Comment by xmedr** [comment]
@hancush @antidipyramid As far as marking an event as streaming, what do you think about adding a new boolean field onto the Broadcast model that denotes whether it was manually created? Then we could have a button on the event's detail page (or elsewhere) that creates a broadcast for the event and sets that field to true. When they're ready to unpublish the link, the button could delete the forced broadcast. And while the link is manually published, we can display an alert visible only to authenticated users to remind Metro to unpublish it when it's done.

My first thought was to add a field onto the Event itself, but that's a proxy model.

**Comment by hancush** [comment]
@xmedr Yes, I think it definitely makes sense to store this info on the EventBroadcast model. In addition to the logic you describe, you'll also need to look at the code that determines whether there is an ongoing meeting and update it to take the manually created broadcasts into account. Does that make sense?

**Comment by xmedr** [comment]
@hancush That does! Sounds great, I'll go with this then
