### ISSUE TITLE
Board/Committee Member Title Edit Feature

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1025]
Can we discuss getting a feature where we can edit Board/Committee Member Titles - similar to how we can edit member's bio?

**Comment by hancush** [comment]
@neilarellano We had the _exact_ same thought! Love this idea.

**Comment by hancush** [comment]
HCG to check whether link between member and area of representation is from Legistar or manually defined in app. If the latter, it would be great for Metro to also be able to manage that.

**Comment by hancush** [comment]
Board member titles are currently defined on the scraper. We use them to create [posts](https://github.com/opencivicdata/python-opencivicdata/blob/1c352a8d246846d1bce976a8c3686ee4f35d0e69/opencivicdata/core/models/people_orgs.py#L239), which are records of a particular position within a legislative body:

- https://github.com/Metro-Records/scrapers-lametro/blob/b7ebaba9a9a17ddce206716dcf19540359c3dd73/lametro/__init__.py#L46
- https://github.com/Metro-Records/scrapers-lametro/blob/b7ebaba9a9a17ddce206716dcf19540359c3dd73/lametro/people.py#L10

Post records are independent of the person holding a position. Instead, they define the possible positions within an organization that are filled by its members.

Each post is associated with a [division](https://github.com/opencivicdata/python-opencivicdata/blob/1c352a8d246846d1bce976a8c3686ee4f35d0e69/opencivicdata/core/models/division.py#L31), which is a political geography.

Each division is assigned a division identifier in the scraper, then the actual geographic shape of the division is associated by the app. This is what shows up on the map.

The Metro board is always comprised of:

- The Mayor of Los Angeles and three appointees 
- Appointees for each of the five Los Angeles County districts
- At least one appointee for each of four [statutorily defined sectors](https://boardagendas.metro.net/static/pdf/CitySelectionCommitte-MTA-Rules-and-Regulations.pdf)  

In recent years, there has also been a (non-voting) appointee by the governor. This structure rarely, if ever, changes. (Is that right, @shrayshray?) It does not make sense to make this manageable, because there are no changes to manage.

Some things have changed, though:

- The country has undergone [redistricting](https://github.com/Metro-Records/la-metro-councilmatic/pull/806/files)
- Titles can vary between members holding the same post

It makes sense to make these things manageable, so they can be updated without DataMade's intervention. Are there other (relatively) frequent changes we want to account for?

**Comment by shrayshray** [comment]
@hancush confirming the structure of the Metro board members "rarely, if ever, changes". It is defined by California Public Utilities Code Section 130051, which was last amended in 1997 and does include a nonvoting member appointed by the Governor - for recent history, this appointee has been the Director of CalTrans District 7.

**Comment by shrayshray** [comment]
All Board members now have their title in their Legistar > People "Notes" field.

**Comment by hancush** [comment]
Superseded by #1045, #1046
