### ISSUE TITLE
Retrieve board member titles from Legistar API

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#1045]
Spinoff from #1025.

Per @shrayshray, all Board members now have their title in their Legistar > People "Notes" field.

![Screenshot 2023-11-27 at 9 32 26 AM](https://github.com/Metro-Records/la-metro-councilmatic/assets/12176173/301fa0dd-6cd4-4f30-9dba-140230aaa0dd)

Let's update the scraper to retrieve title from this field, rather than [manually assigning it](https://github.com/Metro-Records/scrapers-lametro/blob/b7ebaba9a9a17ddce206716dcf19540359c3dd73/lametro/people.py#L10-41). This should also allow Metro to manage post assignment, as we use titles to associate the correct post.

**Comment by antidipyramid** [comment]
12/19 update: We'll wait until the New Year to deploy [this change](https://github.com/Metro-Records/scrapers-lametro/pull/10) to the scrapers.

**Comment by antidipyramid** [comment]
1/4 update: We've deployed the change scraper change to the staging scrapers. After fixing a [bug in an upstream repo](https://github.com/opencivicdata/python-legistar-scraper/pull/123), everything is working as expected. Since it's a Friday, we'll wait until Monday 1/8 to deploy the change to the production scrapers.
