### ISSUE TITLE
1-18-24 Committee Meetings Video Links Not Showing

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1067]
Greetings Team!

Our 1-18-24 Committee Meetings are not showing video links. These videos were made public last Friday. The videos seem to be available insite on both metro.legistar.com and metro.granicus.com. Please see below:

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/77168ae0-19bc-418b-b7b6-42dbcefbcad5)

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/ba81c1ed-da12-43ac-a11c-492f402b3e59)

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/c09db630-d30c-4ce4-a983-8983ccef3b91)

Are we able to investigate this?

Thanks!

**Comment by antidipyramid** [comment]
Hi @neilarellano, the 1-18-24 meetings now have video links, it looks like they came in yesterday evening. Yesterday we did deploy a scraper update to fix an error in the event scraper (more info [here](https://github.com/Metro-Records/scrapers-lametro/issues/12)), so that might have caused the delay. 

We'll keep an eye on the video links for the upcoming meetings.
