### ISSUE TITLE
Error Uploading Katy Yaroslavsky's Portrait

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1073]
I tried uploading a portrait for Director Yaroslavsky but I keep getting an error:
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/a5414835-1bf8-49f9-9158-78d8231140c0)

**Comment by antidipyramid** [comment]
Hi @neilarellano, can you post/send us the image you're trying to upload?

**Comment by neilarellano** [comment]
![Councilwoman Yaroslavsky - Portrait (Jan 2023)](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/8a720340-e05b-471c-a49b-66a72819543c)

Hi @antidipyramid,

Here it is.

**Comment by antidipyramid** [comment]
Update: this is going to require an update to the way we store headshots in the database. We're aiming to have a fix in by the end of the week.

**Comment by antidipyramid** [comment]
Fundamentally, our issues with headshots stem from the fact that we're using the `Person.headshot` field that's defined in [`django-councilmatic`](https://github.com/datamade/django-councilmatic/blob/5b074f376667766e4b6dbf093871d294bb35fc51/councilmatic_core/models.py#L52C1-L62C1):

```python
class Person(opencivicdata.core.models.Person):

    ...

    headshot = models.FileField(upload_to='images/headshots',
                                storage=static_storage,
                                default='images/headshot_placeholder.png')
```

`Person.headshot` hard codes the local filesystem as the storage backend. `LAMetroPerson.headshot_url` tries to get around that by returning the URL in the bucket. After explicitly `councilmatic.custom_storage.MediaStorage` to save the headshot to the S3 bucket, we're stuffing the actual URL of the object in S3 into `LAMetroPerson.headshot`:

```python
    elif "headshot_form" in request.POST:
            form = PersonHeadshotForm(request.POST, instance=person)
            file_obj = request.FILES.get("headshot", "")
            ...
            person.headshot = self.get_file_url(request, file_obj)
            person.save()
```

This sort of works in templates because `LAMetroPerson.headshot_url()` returns the headshot `FileField` itself which converts to the raw URL of the bucket file we passed to it. But because the field isn't using the correct file system, other properties like `LAMetroPerson.headshot.path` or `LAMetroPerson.headshot.size` don't return correctly. 

`LAMetroPerson` is a proxy model so we can't override and change the `headshot` storage backend. 

It seems like there are at least two ways forward:

1. The actual bug we're running into when uploading headshots is the default `max_length=100` constraint on the headshot `FileField`. `councilmatic.custom_storage.MediaStorage` is generating a pre-signed URL for the S3 object which is too long for the `LAMetroPerson.headshot.name`. Since the bucket is public, we could turn off pre-signed URLs for headshots like this:

```python
class MediaStorage(S3Boto3Storage):
    bucket_name = settings.AWS_STORAGE_BUCKET_NAME
    querystring_auth = False
```

2. The above is a bit of a workaround of the problems with `Person.headshot` in `django-councilmatic`. We could alternatively create a new field like `LAMetroPerson.metro_headshot` and customize the field as needed. Though it might be more work, a new headshot field would be a more idiomatic implementation that gets around our current limitations.

It's likely there are more options or other aspects I haven't considered so your thoughts would be greatly appreciated, @hancush and @xmedr!

**Comment by xmedr** [comment]
@antidipyramid I would agree with option two. Since the issue stems from us using a field that's giving us problems that we can't override, making a new field that we have complete control over feels like a solid approach imo.

And if the original headshot field can still return the url, then maybe a data migration would help in reducing the amount of work needed to get the new field off the ground.

**Comment by hancush** [comment]
Hm, @antidipyramid, this seems like a good opportunity to fix the issues you've identified in the upstream library, rather than coding around it here. What if the storage backend were configurable through a Django setting (defaulting to file system, to preserve current behavior), and you increased the max length of the headshot field?

**Comment by antidipyramid** [comment]
@hancush Good call-- I wasn't sure whether we were still making changes to `django-councilmatic`. Adding more flexibility upstream would be the easiest fix.

Just a note: Chicago's councilmatic has transitioned to using [`django-councilmatic`'s `minimal` branch](https://github.com/datamade/django-councilmatic/tree/minimal) and there has been some talk about making the same switch in this instance. Not sure if that changes anything in the short term but we may eventually have to make a similar change to the `minimal` branch if it and `main` remain separate.

**Comment by hancush** [comment]
Hey, @neilarellano – This issue has been addressed. You should now be able to upload headshots to the live site as normal. Please let us know if you encounter any further issues.

**Comment by neilarellano** [comment]
Hi @hancush. I just checked this and can confirm that the upload function is now properly changing the headshots. The headshots seem to be changing properly but I am having some issues viewing the changes while logged in as an admin. The newly uploaded headshot does not display properly until I log out then log back into the site as an admin.

Thanks for the update!

**Comment by hancush** [comment]
Hey, @neilarellano – can you list the steps to reproduce the issue? On my end, when I upload a headshot, it appears immediately on the board member page and in the board members listing. It's possible your browser is caching the old headshots. After you upload, can you try a hard refresh?

**Comment by neilarellano** [comment]
Hi @hancush,

I just tested this out again using a different browser and it seems to be working. You're right about the browser caching the old headshots.

Thanks!
