### ISSUE TITLE
Exclude Public Comment Information for  Special Board Budget Workshop Meetings

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1091]
Greetings!

Are we able to exclude the public comment info for Special Board Budget Workshop meetings please?

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/b86bceab-375c-441b-9311-4f7fdcd18157)

Thanks!

**Comment by xmedr** [comment]
@neilarellano we've added a category of meetings on our side that will not take public comments (live or otherwise) and have added this special board budget meeting to that list.

marking any other meetings that similarly wouldn't want comments would be an easy lift for us going forward, so let us know if there end up being any others!
