### ISSUE TITLE
FY25 Calendar

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1104]
Greetings!

Can we please add a link to the FY25 Calendar.
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/1e86f68c-33fc-453f-b4c7-1751237b7ff8)

Here is the PDF file for the calendar.
[FY25 Committee  Board Calendar.pdf](https://github.com/Metro-Records/la-metro-councilmatic/files/15238822/FY25.Committee.Board.Calendar.pdf)

Thanks!

**Comment by antidipyramid** [comment]
Hi @neilarellano, just making sure: since the FY25 calendar starts in July, do we want to add a link to next year's calendar like this:

<img width="648" alt="Screenshot 2024-05-07 at 1 55 13 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/f5e0e345-0342-4abb-a420-37a88ac15bf7">

or replace the FY24 links with FY25 like this:

<img width="419" alt="Screenshot 2024-05-07 at 1 57 35 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/4be50e91-e44d-47df-8492-20fab1617b7d">

**Comment by camachoo** [comment]
Please add it.  Make it so the FY 25 link stacks below the FY24 link.

example:
[cid:3dc2c334-5ada-4e1f-ac91-0bc908063fed]

________________________________
