### ISSUE TITLE
Board of Directors: Change Map display from Districts, Sectors and City of LA upon member selection

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#482]
On the[ Board of Directors page](https://boardagendas.metro.net/board-members/), is it possible to change the map display from Districts, Sectors and City of LA depending on which Board Member is selected? 
The default on entering the Board of Directors' page is "Districts". When I select someone who represents a District, their district is highlighted; perfect. But when I select someone who is nominated by a Sector, nothing happens on the map. I have to switch the button above the map to "Sectors", then click on the Sector nominee, to see his/her nominating sector. It would be great  to have the map area display automatically switch from District, Sector or City when a member of whichever type is selected. Here's an example where James Butts is selected, but his area is not displaying because we're in the default "Districts" mode:
![image](https://user-images.githubusercontent.com/28063988/63905019-b989c700-c9c7-11e9-83d5-1176789fc563.png)

**Comment by hancush** [comment]
DataMade to also propose a new, more prominent home for the address lookup.

**Comment by hancush** [comment]
Update "Look up Metro Board Member" and/or add example text

**Comment by xmedr** [comment]
Hi @shrayshray I made up a quick wireframe to rearrange some elements of the board members page based off of some comments from our last meeting, and wanted to know what you think!

There was mention of the search bar being slightly hidden on the page, and if this site is for finding your members and their activities, we may want to make this more prominent.

Then, we have some examples of searches for the user underneath the search bar for a clearer idea of how specific you can get.

Last, the "Learn More" tip was moved to the right of the labels since they directly describe them.

![board members page](https://user-images.githubusercontent.com/114717958/216664395-81a7f24a-fc50-49fb-91c3-08db1f7b1b49.png)

**Comment by shrayshray** [comment]
@xmedr this looks great to me! @neilarellano do you have any feedback on the wireframe?

**Comment by neilarellano** [comment]
this makes good use of the available space. I'm always a fan of seeing everything important in one page instead of having to scroll through it

**Comment by neilarellano** [comment]
this new layout puts good emphasis on the search option which I think most people would appreciate
